# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "github-actions"
    groups:
      github-actions:
        patterns: ["*"]
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    groups:
      node-packages:
        patterns: ["*"]
    directory: "/"
    schedule:
      interval: "monthly"
