name: deploy-s3
on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'

jobs:
  push-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repo
        uses: actions/checkout@v2

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_DEPLOY_SECRET_KEY }}
          aws-region: us-east-1

      - name: Update static site files in S3 bucket
        run: aws s3 sync ./src/sophia.quadri.dev s3://sophia.quadri.dev --delete
