name: deploy-s3
on:
  push:
    branches:
      - 'production'
  workflow_dispatch:

jobs:
  push-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Configure npm
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
          cache: 'npm'

      - name: Build static site
        run: |
          npm install
          npm run build

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-access-key-id: ${{ secrets.S3_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_DEPLOY_SECRET_KEY }}
          aws-region: us-east-1

      - name: Update static site files in S3 bucket
        run: aws s3 sync ./dist s3://sophia.quadri.dev --delete
